#ifndef TPFINALAYDAI_ALGOR_COMPARISONRESULT_HPP
#define TPFINALAYDAI_ALGOR_COMPARISONRESULT_HPP

namespace algor {
    enum ComparisonResult : int {
        LESS = -1, EQUAL = 0, GREATER = 1
    };
}

#endif //TPFINALAYDAI_ALGOR_COMPARISONRESULT_HPP
